<div class="error">
    <p>
        <?php if (isset($Params['Error'])) echo $Params['Error']; ?>
    </p>
    <script type="text/javascript" src="/templates/js/jquery.ui.widget.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.fileupload.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.cloudinary.js"></script>
    <?php

    use Cloudinary\Tag\JsConfigTag;

    echo new JsConfigTag();
    ?>
</div>
<div class="container prof-block">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                <div class="prof-img-container">
                    <?php

                    use Cloudinary\Tag\ImageTag;
                    use Cloudinary\Asset\Image;
                    use Cloudinary\Transformation\Resize;

                    $path = $Params['AvatarPath'];
                    preg_match('/\/([^\/]*)\./', $path, $matches);
                    if (!empty($matches[1])) {
                        $path = $matches[1];
                    }

                    echo (new ImageTag(new Image($path)))->resize(Resize::fit(350, 250));

                    ?>
                </div>
                <form method="post" action="/Users/ChangePass/">
                    <p>Змінити пароль</p>
                    <div class="form-group">
                        <input type="password" name="password" id="password" class="form-control required" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{0,60}" title="Має містити символи різних регістрів та як мінімум 6 символів" placeholder="Старий пароль">
                    </div>
                    <div class="form-group">
                        <input type="password" name="passwordNew" id="passwordNew" class="form-control required" placeholder="Новий пароль">
                    </div>
                    <div class="prof-but">
                        <input type="submit" class="sendEdit pass-but" value="Змінити">
                    </div>
                </form>
            </div>
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                <div class="container prof-container">
                    <h2><?php echo $Params['FirstName'] . ' ' . $Params['SecondName'] ?></h2>
                </div>
                <hr>
                <form enctype="multipart/form-data" method="post" action="/Users/EditProf/">
                    <ul class="container details edit-block">
                        <?php
                        echo "<li><p><span class='glyphicon glyphicon-user one prof-icon'></span>Логин</p>
                    <input type='text' name='login' id='login' class='form-control required' pattern='.{2,50}' title='2-50 символів' required
                           value='" . $Params['Login'] . "'/></li>";
                        echo "<li><p><span class='glyphicon glyphicon-envelope one prof-icon'></span>Mail</p>
                        <input type='text' name='mail' id='mail' class='form-control required' pattern='[A-Za-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$' required
                               value='" . $Params['Mail'] . "'/></li>";
                        echo "<li><p><span class='glyphicon glyphicon-globe prof-icon'></span>Країна</p>
                        <input type='text' name='country' id='country' class='form-control' title='0-40 символів' pattern='.{0,40}'
                               value='" . $Params['Country'] . "'/></li>";
                        echo "<li><p><span class='glyphicon glyphicon-map-marker one prof-icon'></span>Місто</p>
                        <input type='text' name='city' id='city' class='form-control' title='0-40 символів' pattern='.{0,40}'
                               value='" . $Params['City'] . "'/></li>";
                        echo "<li><p><span class='glyphicon glyphicon-calendar prof-icon'></span>Дата народження</p>
                        <input type='date' name='birthDate' id='birthDate' class='form-control'
                               value='" . $Params['BirthDate'] . "'/></li>";
                        echo "<li><p><span class='glyphicon glyphicon-book prof-icon'></span>Про себе</p>
                            <textarea name='shortDescription' id='shortDescription' class='form-control'>" . $Params['ShortDescription'] . "</textarea></li>";
                        ?>
                        <li>
                            <p><span class='glyphicon glyphicon-picture prof-icon'></span>Аватар</p>
                            <label for='avatarPath' class='btn btn-large custom-file-label '>Змінити фото профіля</label>
                            <?php

                            use Cloudinary\Tag\UploadTag;

                            echo (new UploadTag('avatarPath'))->setAttribute(
                                'id',
                                'avatarPath'
                            );;
                            ?>
                            <img src='' id='imagePreview' class='hid-img' alt='Preview Image' />
                            <input type='button' name='canAvatar' id='canAvatar' class='hide' />
                            <label for='canAvatar' class='btn btn-large custom-file-label hid-img btn-auto' id='canAvatarLabel'>Скинути</label>
                            <br><label for='info' class='btn custom-file-label'>Видалити аватар<input type='checkbox' id='info' name='deleteAva' class='badgebox'><span class='badge'>&check;</span></label>
                        </li>

                    </ul>
                    <div class="prof-but">
                        <input type="submit" class="sendEdit" value="Зберегти зміни">
                    </div>
                </form>
            </div>
        </div>

        <script>
            $(function() {
                if ($.fn.cloudinary_fileupload !== undefined) {
                    $("input.cloudinary-fileupload[type=file]").cloudinary_fileupload();
                }
            });
        </script>
    </div>