<div class="error">
    <p>
        <?php if (isset($Params['Error'])) echo $Params['Error']; ?>
    </p>
    <script type="text/javascript" src="/templates/js/jquery.ui.widget.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.fileupload.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.cloudinary.js"></script>
    <?php

    use Cloudinary\Tag\JsConfigTag;

    echo new JsConfigTag();
    ?>
</div>
<div class="container prof-block">
    <div class="edit-profile">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                <div class="prof-img-container">
                    <?php

                    use Cloudinary\Tag\ImageTag;
                    use Cloudinary\Asset\Image;
                    use Cloudinary\Transformation\Resize;

                    $path = $Params['AvatarPath'];
                    preg_match('/\/([^\/]*)\./', $path, $matches);
                    if (!empty($matches[1])) {
                        $path = $matches[1];
                    }

                    echo (new ImageTag(new Image($path)))->resize(Resize::fit(350, 250));

                    ?>
                </div>
                <form method="post" action="/Users/ChangePass/">
                    <br />
                    <p>Змінити пароль</p>
                    <div class="form-group">
                        <input type="password" name="password" id="password" class="form-control" pattern="(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{0,60}" title="Має містити символи різних регістрів та як мінімум 6 символів" placeholder="Старий пароль">
                    </div>
                    <div class="form-group">
                        <input type="password" name="passwordNew" id="passwordNew" class="form-control" placeholder="Новий пароль">
                    </div>
                    <div class="prof-but">
                        <input type="submit" class="sendEdit btn btn-raised btn-danger btn-prof-set btn-add-post" value="Змінити">
                    </div>
                </form>
            </div>
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                <div class="container prof-container">
                    <h2><?php echo $Params['FirstName'] . ' ' . $Params['SecondName'] ?></h2>
                </div>
                <br />
                <form enctype="multipart/form-data" method="post" action="/Users/EditProf/">
                    <ul class="container details edit-block">
                        <input style="display: none;" type='text' name='login' id='login' class='form-control' pattern='.{2,50}' title='2-50 символів' required value='<?php echo $Params['Login']; ?>' />
                        <li>
                            <p><span class='glyphicon glyphicon-user one prof-icon'></span>Ім'я</p>
                            <input type='text' name='firstName' id='firstName' class='form-control' pattern='.{2,50}' title='2-50 символів' required value='<?php echo $Params['FirstName']; ?>' />
                        </li>
                        <?php echo "<li><p><span class='glyphicon glyphicon-user one prof-icon'></span>Прізвище</p>
                        <input type='text' name='secondName' id='secondName' class='form-control ' pattern='.{2,50}' title='2-50 символів' required
                                value='" . $Params['SecondName'] . "'/></li>";
                        echo "<li><p><span class='glyphicon glyphicon-envelope one prof-icon'></span>Mail</p>
                        <input type='text' name='mail' id='mail' class='form-control' pattern='[A-Za-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$' required
                               value='" . $Params['Mail'] . "'/></li>"; ?>
                        <li>
                            <p><span class='glyphicon glyphicon-globe prof-icon'></span>Країна</p>
                            <select name='country' id='country' class='form-control' required>
                                <option value="Україна" <?php if ($Params['Country'] == 'Україна'): ?>selected="selected"<?php endif; ?>>Україна</option>
                                <option value="Росія" <?php if ($Params['Country'] == 'Росія'): ?>selected="selected"<?php endif; ?>>Росія</option>
                                <option value="Білорусь" <?php if ($Params['Country'] == 'Білорусь'): ?>selected="selected"<?php endif; ?>>Білорусь</option>
                                <option value="Молдова" <?php if ($Params['Country'] == 'Молдова'): ?>selected="selected"<?php endif; ?>>Молдова</option>
                                <option value="Польша" <?php if ($Params['Country'] == 'Польша'): ?>selected="selected"<?php endif; ?>>Польша</option>
                                <option value="Вірменія" <?php if ($Params['Country'] == 'Вірменія'): ?>selected="selected"<?php endif; ?>>Вірменія</option>
                                <option value="Казахстан" <?php if ($Params['Country'] == 'Казахстан'): ?>selected="selected"<?php endif; ?>>Казахстан</option>
                                <option value="Грузія" <?php if ($Params['Country'] == 'Грузія'): ?>selected="selected"<?php endif; ?>>Грузія</option>
                                <option value="Інша" <?php if ($Params['Country'] == 'Інша'): ?>selected="selected"<?php endif; ?>>Інша</option>
                            </select>
                        </li>
                        <li><p><span class='glyphicon glyphicon-map-marker one prof-icon'></span>Місто</p>
                            <input type='text' name='city' id='city' class='form-control' title='0-40 символів' pattern='.{0,40}' required
                               value='<?php echo $Params['City']; ?>'/></li>
                        <li><p><span class='glyphicon glyphicon-calendar prof-icon'></span>Дата народження</p>
                            <input type='date' name='birthDate' id='birthDate' required class='form-control'
                               value='<?php echo $Params['BirthDate']; ?>'/>
                        </li>
                        <li>
                            <p><span class='glyphicon  glyphicon-question-sign prof-icon'></span>Стать</p>
                            <select name='sex' id='sex' class='form-control' required>
                                <option value="f" <?php if ($Params['Sex'] == 'f'): ?>selected="selected"<?php endif; ?>>Жіноча</option>
                                <option value="m" <?php if ($Params['Sex'] == 'm'): ?>selected="selected"<?php endif; ?>>Чоловіча</option>
                            </select>
                        </li>

                         <?php echo "<li><p><span class='glyphicon glyphicon-book prof-icon'></span>Про себе</p>
                            <textarea required name='shortDescription' id='shortDescription' class='form-control'>" . $Params['ShortDescription'] . "</textarea></li>";
                        ?>
                        <li>
                            <p><span class='glyphicon glyphicon-picture prof-icon'></span>Аватар</p>
                            <label for='avatarPath' class='btn btn-large custom-file-label '>Змінити фото профіля</label>
                            <?php

                            use Cloudinary\Tag\UploadTag;

                            echo (new UploadTag('avatarPath'))->setAttribute(
                                'id',
                                'avatarPath'
                            );;
                            ?>
                            <img src='' id='imagePreview' class='hid-img' alt='Preview Image' />
                            <input type='button' name='canAvatar' id='canAvatar' class='hide' />
                            <label for='canAvatar' class='btn btn-large custom-file-label hid-img btn-auto' id='canAvatarLabel'>Скинути</label>
                            <br><label for='info' class='btn custom-file-label'>Видалити аватар<input type='checkbox' id='info' name='deleteAva' class='badgebox'><span class='badge'>&check;</span></label>
                        </li>

                    </ul>
                    <div class="prof-but">
                        <input type="submit" class="sendEdit btn btn-raised btn-danger btn-prof-set btn-add-post" value="Зберегти зміни">
                    </div>
                </form>
            </div>
        </div>

        <script>
            $(function() {
                if ($.fn.cloudinary_fileupload !== undefined) {
                    $("input.cloudinary-fileupload[type=file]").cloudinary_fileupload();
                }
            });
        </script>
    </div>