<div class="container prof-block">
    <div class="profile-view">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                <div class="prof-img-container">
                    <?php

                    use Cloudinary\Tag\ImageTag;
                    use Cloudinary\Asset\Image;
                    use Cloudinary\Transformation\Resize;

                    $path = $Params['AvatarPath'];
                    preg_match('/\/([^\/]*)\./', $path, $matches);
                    if (!empty($matches[1])) {
                        $path = $matches[1];
                    }

                    echo (new ImageTag(new Image($path)))->resize(Resize::fit(350, 250));

                    ?>
                </div>
                <div class="float-left small prof-but">
                    <a class="btn btn-raised btn-danger btn-prof-set" href="/Users/DeleteUser/">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                    </a>
                    <a class="btn btn-raised btn-danger btn-prof-set" href="/Users/EditProf/">
                        <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                    </a>
                    <a class="btn btn-raised btn-danger btn-prof-set" href="/Analytics/Index/">
                        <span class="glyphicon glyphicon-stats" aria-hidden="true"> Статистика</span>
                    </a>
                </div>
            </div>
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                <div class="container prof-container">
                    <h2><?php echo $Params['Login']; ?></h2>
                </div>
                <div class="container details">
                    <div>
                        <p><span class='glyphicon glyphicon-user one prof-icon'></span><?php echo $Params['FirstName'] . " " . $Params['SecondName']; ?></p>
                    </div>
                    <div>
                        <p><span class='glyphicon glyphicon-envelope one prof-icon'></span><?php echo $Params['Mail']; ?></p>
                    </div>
                    <?php if (isset($Params['Country']) && $Params['Country'] != '') : ?>
                        <div>
                            <p>
                                <span class='glyphicon glyphicon-globe prof-icon'></span><?php echo $Params['Country']; ?>
                                <?php if (isset($Params['City']) && $Params['City'] != '') : ?>
                                    <span>, </span><?php echo $Params['City']; ?>
                                <?php endif; ?>
                            </p>
                        </div>
                    <?php endif; ?>
                    <?php if (isset($Params['BirthDate']) && $Params['BirthDate'] != '0000-00-00') : ?>
                        <div>
                            <p><span class='glyphicon glyphicon-calendar prof-icon'></span><?php echo $Params['BirthDate']; ?></p>
                        </div>
                    <?php endif; ?>
                    <?php if (isset($Params['ShortDescription'])) : ?>
                        <div>
                            <p><span class='glyphicon glyphicon-book  prof-icon'></span><?php echo $Params['ShortDescription']; ?></p>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>