<div class="container prof-block">
    <script type="text/javascript" src="/templates/js/jquery.ui.widget.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.fileupload.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.cloudinary.js"></script>
    <?php

    use Cloudinary\Tag\JsConfigTag;

    echo new JsConfigTag();
    ?>
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <div class="post-container">
        <div class="row">
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8 post-adding">
                <form id='addPost' class="form" method="post" action="/Posts/Add/" enctype="multipart/form-data">
                    <p class="title">
                        <span class='fa fa-header'> Заголовок</span>
                        <input type='text' name='name' id='name' pattern=".{0,50}" title="2-50 символів" class='form-control' />
                    </p>
                    <p>
                        <span class='fa fa-quote-left'> Текст</span>
                        <input style='display:none' name='text' id='text' class='form-control textarea-item' />
                        <input style='display:none' name='textOnly' id='textOnly' class='form-control textarea-item' />
                        <div id='editor'></div>
                    </p>
                    <p class="poster">
                        <span class='fa fa-camera-retro'> Постер</span>
                        <label for='posterPath' class='btn btn-large custom-file-label '>Додати фото</label>
                        <img src='' id='imagePreview' class='hid-img' alt='Preview Image' />
                        <?php

                        use Cloudinary\Tag\UploadTag;

                        echo (new UploadTag('posterPath'))->setAttribute(
                            'id', 'posterPath'
                        );;
                        ?>
                        <input type='button' name='canAvatar' id='canAvatar' class='hide' />
                        <label for='canAvatar' class='btn btn-large custom-file-label hid-img btn-auto' id='canAvatarLabel'>Скинути</label>
                    </p>
                    <div class="add-submit">
                        <input type="submit" value="Створити" class="btn btn-raised btn-danger btn-prof-set btn-add-post" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
    <script>
        $(function() {
            if ($.fn.cloudinary_fileupload !== undefined) {
                $("input.cloudinary-fileupload[type=file]").cloudinary_fileupload();
            }
        });

        var quill = new Quill('#editor', {
            theme: 'snow',
            placeholder: 'Enter text...',
        });

        $("#addPost").on("submit", function(e) {
            $("input#text").val(quill.root.innerHTML)
            $("input#textOnly").val(quill.getText())
        })
    </script>
</div>