<div class="container prof-block">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

    <div class="jumbotron post-container">
        <div class="row">
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8 post-adding">
                <form id='addPost' class="form" method="post" action="/Posts/Add/" enctype="multipart/form-data">
                    <p>
                        <span class='fa fa-film  fa-review'>Назва</span>
                        <input type='text' name='name' id='name' pattern=".{0,50}" title="2-50 символів" class='form-control' />
                    </p>
                    <p>
                        <span class='fa fa fa-sticky-note-o fa-review'>Текст</span>
                        <input style='display:none' name='text' id='text' class='form-control textarea-item' />
                        <input style='display:none' name='textOnly' id='textOnly' class='form-control textarea-item' />
                    <div id='editor'></div>
                    </p>
                    <p>
                        <span class='fa fa fa-file fa-review'> Постер</span>
                        <input type='file' name='poster' id='imageUpload' class='hide img-input form-control-file' />
                        <label for='imageUpload' class='btn btn-large custom-file-label '>Додати фото</label>
                        <img src='' id='imagePreview' class='hid-img' alt='Preview Image' />
                        <input type='button' name='canAvatar' id='canAvatar' class='hide' />
                        <label for='canAvatar' class='btn btn-large custom-file-label hid-img btn-auto' id='canAvatarLabel'>Скинути</label>
                    </p>
                    <div>
                        <input type="submit" value="Створити" class="btn btn-block but-create" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
    <script>
        var quill = new Quill('#editor', {
            theme: 'snow',
            placeholder: 'Enter text...',
        });

        $("#addPost").on("submit", function(e) {
            $("input#text").val(quill.root.innerHTML)
            $("input#textOnly").val(quill.getText())
        })
    </script>
</div>