<div class="container prof-block">
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

    <script type="text/javascript" src="/templates/js/jquery.ui.widget.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.fileupload.js"></script>
    <script type="text/javascript" src="/templates/js/jquery.cloudinary.js"></script>
    <?php

    use Cloudinary\Tag\JsConfigTag;

    echo new JsConfigTag();
    ?>

    <div class="post-container">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                <div class="prof-img-container">
                    <?php

                    use Cloudinary\Tag\ImageTag;
                    use Cloudinary\Asset\Image;
                    use Cloudinary\Transformation\Resize;

                    $path = $Params['PosterPath'];
                    preg_match('/\/([^\/]*)\./', $path, $matches);
                    if (!empty($matches[1])) {
                        $path = $matches[1];
                    }

                    echo (new ImageTag(new Image($path)))->resize(Resize::fit(350, 250));

                    ?>

                </div>
                <div>
                    <?php
                    if (isset($Params['PublicationDate']) && $Params['PublicationDate'] != '0000-00-00')
                        echo "
                    <br/><p class='publication-date'><span class='fa fa-calendar-plus-o'></span> " . date('d-m-Y', strtotime($Params['PublicationDate'])) . "</p>
                    "; ?>
                </div>
            </div>
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8 post-editing">
                <form id='editPost' class="form" method="post" action="/Posts/Edit/?Id=<?php echo $Params['Id']; ?>" enctype="multipart/form-data">
                    <?php echo "<p><span class='fa fa-header'> Назва</span><input type='text' name='name' id='name' pattern='.{0,50}'  title='2-50 символів'
                                                                               class='form-control' value='" . $Params['Name'] . "'/></p>"; ?>
                    <p>
                        <span class='fa fa-quote-left'> Текст</span>
                        <input style='display:none' name='text' id='text' class='form-control textarea-item' />
                        <input style='display:none' name='textOnly' id='textOnly' class='form-control textarea-item' />
                    <div id='editor'></div>
                    </p>
                    <p class="category">
                        <span class='fa fa-th-larg'> Категорія</span>
                        <select name='categoryId' id='categoryId' required class='form-control'>
                            <?php foreach ($Params['Categories'] as $category) : ?>
                                <option id='category-<?= $category['Id'] ?>' value='<?= $category['Id'] ?>' <?php if ($category['Id'] == $Params['categoryId']): ?>selected<?php endif;?>>
                                    <?= $category['Name'] ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </p>
                    <p><span class='fa fa-camera-retro'> Постер</span>
                        <label for='posterPath' class='btn btn-large custom-file-label '>Змінити</label>
                        <img src='' id='imagePreview' class='hid-img' alt='Preview Image' />
                        <?php

                        use Cloudinary\Tag\UploadTag;

                        echo (new UploadTag('posterPath'))->setAttribute(
                            'id',
                            'posterPath'
                        );;
                        ?>
                        <input type='button' name='canAvatar' id='canAvatar' class='hide' />
                        <label for='canAvatar' class='btn btn-large custom-file-label hid-img btn-auto' id='canAvatarLabel'>Скинути</label>
                        <label for='info' class='btn custom-file-label'>Видалити постер<input type='checkbox' id='info' name='deleteAva' class='badgebox'><span class='badge'>&check;</span></label>
                    </p>
                    <div class="add-submit">
                        <input type='submit' value="Редагувати" class="btn btn-raised btn-danger btn-prof-set btn-add-post" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
    <script>
        $(function() {
            if ($.fn.cloudinary_fileupload !== undefined) {
                $("input.cloudinary-fileupload[type=file]").cloudinary_fileupload();
            }
        });

        var quill = new Quill('#editor', {
            theme: 'snow',
            placeholder: 'Enter text...',
        });

        const value = '<?php echo html_entity_decode($Params['Text']) ?>'
        const delta = quill.clipboard.convert(value)

        quill.setContents(delta, 'silent')

        $("#editPost").on("submit", function(e) {
            $("input#text").val(quill.root.innerHTML)
            $("input#textOnly").val(quill.getText())
        })
    </script>
</div>