<div class="container prof-block">
    <div class="post-container">
        <div class="row">
            <div class="">
                <div class="container prof-container">
                    <h2><?php if (isset($Params['Name'])) echo $Params['Name']; ?></h2>
                </div>
                <hr>
            </div>
            <div class="post-text">
                <p><?php
                    if (isset($Params['Text']) && $Params['Text'] != '')
                        echo $Params['Text']; ?>
                </p>
            </div>
            <div class="">
                <div>
                    <?php
                    if (isset($Params['PublicationDate']) && $Params['PublicationDate'] != '0000-00-00')
                        echo "
                    <p><span class='fa fa-calendar-plus-o'></span>" . $Params['PublicationDate'] . "</p>
                    "; ?>
                </div>
            </div>
        </div>


        <div class="comments-row">
            <?php foreach ($Params['Comments'] as $comment) : ?>
                <div class="comment-item">
                    <div class="comment-user">
                        <a href='/Posts/User/<?= $comment['Author']['Login'] ?>'>
                            <img width="25" height="25" src='<?= $comment['Author']['AvatarPath'] ?>' />
                            <span><?= $comment['Author']['Login'] ?></span>
                            <span><?= $comment['commentDate'] ?></span>
                        </a>
                    </div>
                    <div class="comment-content">
                        <span><?= $comment['commentText'] ?></span>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</div>