<?php if ($_SESSION['login'] == 'admin')
    echo "<a class='btn btn-raised btn-danger btn-prof-set btn-add-review' href='/Posts/Add/'>
    <span class='glyphicon glyphicon-plus' aria-hidden='true'>Додати</span>
</a>"; ?>
<div class="row content-row review-block">
    <?php
    foreach ($Params['Content'] as $key) {
        $path = $key['PosterPath'];
        if ($path == '')
            $path = '/files/standarts/reviewPoster.jpg';
        echo "<div class='post-item'>";
        if ($key['isUserPost'])
            echo "
        <div class='admin-panel'>
            <a class='btn btn-raised btn-danger btn-prof-set' href='/Posts/Delete/?Id=" . $key['Id'] . "'>
                <span class='glyphicon glyphicon-remove' aria-hidden='true'></span>
            </a>
            <a class='btn btn-raised btn-danger btn-prof-set' href='/Posts/Edit/?Id=" . $key['Id'] . "'>
                <span class='glyphicon glyphicon-edit' aria-hidden='true'></span>
            </a>
        </div>";
        echo "<div class='img-container'><img class='film-poster' src='" . $path . "'></div>
    <div class='text-container'><a class='film-link' href='/Posts/Show/?Id=" . $key['Id'] . "'>" . $key['Name'] . "</a></div>
    </div>";
    }
    echo "</div>";
    echo "<div class='pagination-div'><ul class='pagination'>
        <li><a href='/Posts/Index/?page=1'>«</a></li>
        ";
    for ($i = 1; $i <= $Params['PagesCount']; $i++) {
        if ($Params['CurrentPage'] == ($i - 1))
            echo "<li class='active'><a href='/Posts/Index/?page=" . $i . "'>" . $i . "</a></li>";
        else
            echo "<li><a href='/Posts/Index/?page=" . $i . "'>" . $i . "</a></li>";
    }
    echo ("<li><a href='/Posts/Index/?page=" . $Params['PagesCount'] . "'>»</a></li></ul>"); ?>
</div>