<?php

use Cloudinary\Tag\ImageTag;
use Cloudinary\Asset\Image;
use Cloudinary\Transformation\Resize;

$isCurrentUserPost = !!($_SESSION['login'] ==  $Params['Author']['Login']); ?>

<div class="posts-container prof-block">
    <div class="user-row sticky">
        <?php

        $ownerPath = $Params['Author']['AvatarPath'];
        preg_match('/\/([^\/]*)\./', $ownerPath, $matches);
        if (!empty($matches[1])) {
            $ownerPath = $matches[1];
        }

        $path =$Params['PosterPath'];
        preg_match('/\/([^\/]*)\./', $path, $matches);
        if (!empty($matches[1])) {
            $path = $matches[1];
        }
        echo (new ImageTag(new Image($ownerPath)))->resize(Resize::fit(200, 200));
        ?>
        <div class="user-info">
            <div class="login"><?= $Params['Author']['Login'] ?></div>
            <div class="location"><?= $Params['Author']['Country'] . ', ' . $Params['Author']['City']; ?></div>
            <div class="about"><?= $Params['Author']['ShortDescription']; ?></div>
            <div>
                <?php if (!$isCurrentUserPost && $Params['Subscription']) : ?>
                    <a class="unfollow-link" href='/Subscriptions/Delete/?follow=<?= $Params['Author']['Login'] ?>'>Unfollow</a>
                    <a style="display: none;" class="follow-link" href='/Subscriptions/Add/?follow=<?= $Params['Author']['Login'] ?>'>Follow</a>
                <?php elseif (!$isCurrentUserPost && !$Params['Subscription']) : ?>
                    <a class="follow-link" href='/Subscriptions/Add/?follow=<?= $Params['Author']['Login'] ?>'>Follow</a>
                    <a style="display: none;" class="unfollow-link" href='/Subscriptions/Delete/?follow=<?= $Params['Author']['Login'] ?>'>Unfollow</a>
                <?php endif; ?>
            </div>
        </div>

        <?php if ($isCurrentUserPost) : ?>
            <a class='btn btn-raised btn-danger btn-prof-set btn-add-post' href='/Posts/Add/'>
                <span class='glyphicon glyphicon-plus' aria-hidden='true'>Додати</span>
            </a>
        <?php endif; ?>
    </div>

    <div class="posts-block">
        <div>
            <div class="">
                <div class="post-title">
                    <h2><?php if (isset($Params['Name'])) echo $Params['Name']; ?></h2>
                </div>
                <hr>
            </div>
            <?php if($path != 'utj4t4fmibagpqcn9543'):?>
                <div class="post-poster">
                    <?php echo (new ImageTag(new Image($path)))->resize(Resize::fit(692, 375)); ?>
                </div>
            <?php endif; ?>
            <div class="post-text">
                <p><?php
                    if (isset($Params['Text']) && $Params['Text'] != '')
                        echo  html_entity_decode($Params['Text']); ?>
                </p>
            </div>
            <br/>
            <div class='likes-container'>
                <div class="rating-items">
                    <?php if ($Params['LikesUser']) : ?>
                        <a class="unlike-link" href='/Likes/Delete/?post=<?= $Params['Id'] ?>'>
                            <span class='likes glyphicon glyphicon-heart'><?= $Params['LikesCount']; ?></span>
                        </a>
                        <a style="display: none;" class="like-link" href='/Likes/Add/?post=<?= $Params['Id'] ?>'>
                            <span class='likes glyphicon glyphicon-heart-empty'><?= $Params['LikesCount'] - 1; ?></span>
                        </a>
                    <?php else : ?>
                        <a class="like-link" href='/Likes/Add/?post=<?= $Params['Id'] ?>'>
                            <span class='likes glyphicon glyphicon-heart-empty'><?= $Params['LikesCount']; ?></span>
                        </a>
                        <a style="display: none;" class="unlike-link" href='/Likes/Delete/?post=<?= $Params['Id'] ?>'>
                            <span class='likes glyphicon glyphicon-heart'><?= $Params['LikesCount'] + 1; ?></span>
                        </a>
                    <?php endif; ?>
                    <span class='comments glyphicon glyphicon-comment'><?= count($Params['Comments']); ?></span>
                </div>
                <div class="publication-date">
                    <?php
                    if (isset($Params['PublicationDate']) && $Params['PublicationDate'] != '0000-00-00')
                        echo "
                        <span class='fa fa-calendar-plus-o'></span> " . date('d-m-Y', strtotime($Params['PublicationDate'])); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="comments-row">
    <form id='addComment' class="form" method="post" action="/Comments/Add/" enctype="multipart/form-data">
        <input style='display:none' type="hidden" name='postId' id='postId' class='form-control' value="<?= $Params['Id']; ?>" />
        <div class="form-group">
            <textarea name="commentText" id="commentText" required class="form-control" placeholder="Додати коментар"></textarea>
        </div>
        <div class="comment-submit">
            <input type="submit" value="Надіслати" class="btn btn-block btn-prof-set" />
        </div>
    </form>
    <?php foreach ($Params['Comments'] as $comment) : 
        
        $authorPath = $comment['Author']['AvatarPath'];
        preg_match('/\/([^\/]*)\./', $authorPath, $matches);
        if (!empty($matches[1])) {
            $authorPath = $matches[1];
        }
        ?>

        <div class="comment-item">
            <div class="comment-user">
                <a class="author-link" href='/Posts/User/<?= $comment['Author']['Login'] ?>'>
                    <?php echo (new ImageTag(new Image($authorPath)))->resize(Resize::fit(25, 25)); ?>
                    <span><?= $comment['Author']['Login'] ?></span>
                </a>
                <span class="publication-date"><?= $comment['commentDate'] ?></span>
            </div>
            <div class="comment-content">
                <span><?= $comment['commentText'] ?></span>
            </div>
            <?php if ($comment['Author']['Login'] == $_SESSION['login']) : ?>
                <div class="delete-comment">
                    <a href='/Comments/Delete/?Id=<?= $comment['Id'] ?>'>Delete</a>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach ?>
</div>

<?php if ($Params['Author']['Login'] != $_SESSION['login']) : ?>
    <script src="/templates/js/posts/addView.js"></script>
<?php endif; ?>
<script src="/templates/js/posts/comments.js"></script>