<div class="row content-row post-block posts-main">
    <?php

    use Cloudinary\Tag\ImageTag;
    use Cloudinary\Asset\Image;
    use Cloudinary\Transformation\Resize;

    foreach ($Params['Content'] as $key) :
        $path = $key['PosterPath'];
        preg_match('/\/([^\/]*)\./', $path, $matches);
        if (!empty($matches[1])) {
            $path = $matches[1];
        }
        $authorPath = $key['AuthorImage'];
        preg_match('/\/([^\/]*)\./', $authorPath, $matches);
        if (!empty($matches[1])) {
            $authorPath = $matches[1];
        }
    ?>

        <div class='post-item'>
            <div class='img-container'>
                <div class="">
                    <?php echo (new ImageTag(new Image($path)))->resize(Resize::fit(277, 150)); ?>
                </div>
                <?php if ($key['isUserPost']) : ?>
                    <div class='admin-panel'>
                        <a class='btn btn-raised btn-danger btn-prof-set' href='/Posts/Delete/?Id=<?= $key['Id']; ?>'>
                            <span class='glyphicon glyphicon-remove' aria-hidden='true'></span>
                        </a>
                        <a class='btn btn-raised btn-danger btn-prof-set' href='/Posts/Edit/?Id=<?= $key['Id']; ?>'>
                            <span class='glyphicon glyphicon-edit' aria-hidden='true'></span>
                        </a>
                    </div>
                <?php endif; ?>
            </div>
            <div class='text-container'>
                <div class="user-pict">
                    <a class='author-link' href='/Posts/User/<?= $key['Author']; ?>'>
                        <?php echo (new ImageTag(new Image($authorPath)))->resize(Resize::fit(30, 30)); ?>
                        <span><?= $key['Author']; ?></span>
                    </a>
                </div>
                <a class='post-link' href='/Posts/Show/?Id=<?= $key['Id']; ?>'><?= $key['Name']; ?></a>
                <div class='post-content'><?= html_entity_decode($key['Text']); ?></div>
                <div class='likes-container'>
                    <div class="rating-items">
                        <?php if ($key['LikesUser']) : ?>
                            <a class="unlike-link" href='/Likes/Delete/?post=<?= $key['Id'] ?>'>
                                <span class='likes glyphicon glyphicon-heart'><?= $key['LikesCount']; ?></span>
                            </a>
                            <a style="display: none;" class="like-link" href='/Likes/Add/?post=<?= $key['Id'] ?>'>
                                <span class='likes glyphicon glyphicon-heart-empty'><?= $key['LikesCount'] - 1; ?></span>
                            </a>
                        <?php else : ?>
                            <a class="like-link" href='/Likes/Add/?post=<?= $key['Id'] ?>'>
                                <span class='likes glyphicon glyphicon-heart-empty'><?= $key['LikesCount']; ?></span>
                            </a>
                            <a style="display: none;" class="unlike-link" href='/Likes/Delete/?post=<?= $key['Id'] ?>'>
                                <span class='likes glyphicon glyphicon-heart'><?= $key['LikesCount'] + 1; ?></span>
                            </a>
                        <?php endif; ?>
                        <span class='comments glyphicon glyphicon-comment'><?= $key['CommentsCount']; ?></span>
                    </div>
                    <div class="publication-date">
                        <span><?= date('d-m-Y', strtotime($key['PublicationDate'])); ?></span>
                    </div>
                </div>
            </div>
        </div>
    <?php endforeach ?>
</div>


<div class='pagination-div'>
    <ul class='pagination'>
        <li><a href='/Posts/Index/?page=1'>«</a></li>
        <?php for ($i = 1; $i <= $Params['PagesCount']; $i++) {
            if ($Params['CurrentPage'] == ($i - 1)) : ?>
                <li class='active'><a href='/Posts/Index/?page=<?= $i; ?>'><?= $i; ?></a></li>
            <?php else : ?>
                <li><a href='/Posts/Index/?page=<?= $i; ?>'><?= $i; ?></a></li>
        <?php endif;
        } ?>
        <li><a href='/Posts/Index/?page=<?= $Params['PagesCount'] ?>'>»</a></li>
    </ul>
</div>

<script src="/templates/js/posts/like.js"></script>