<div class="tabs">
    <ul class="tabs__caption">
        <li class="active">Пости</li>
        <li>Користувачі</li>
    </ul>


    <div class="row content-row post-block tabs__content active">
        <?php

        use Cloudinary\Tag\ImageTag;
        use Cloudinary\Asset\Image;
        use Cloudinary\Transformation\Resize;

        foreach ($Params['Content'] as $key) :
            $path = $key['PosterPath'];
            preg_match('/\/([^\/]*)\./', $path, $matches);
            if (!empty($matches[1])) {
                $path = $matches[1];
            }
        ?>
            <div class="user-search">
                <div class='img-container'>
                    <div>
                        <?php
                            echo (new ImageTag(new Image($path)))->resize(Resize::fit(277, 150));
                        ?>
                    </div>
                    <span> <?= $key['PublicationDate']; ?></span>
                </div>
                <div class='text-container'>
                    <div>
                        <img width="30" height="30" class='user-logo' src='<?= $key['Author']['AuthorImage']; ?>'>
                        <a class='author-link' href='/Posts/User/<?= $key['Author']['Login']; ?>'><?= $key['Author']['Login']; ?></a>
                    </div>
                    <a class='poster-link' href='/Posts/Show/?Id=<?= $key['Id']; ?>'>
                        <?= $key['Name']; ?>
                    </a>
                    <?= html_entity_decode($key['Text']); ?>
                </div>
            </div>
        <?php endforeach ?>
    </div>

    <div class="row content-row users-block tabs__content">
        <?php foreach ($Params['users'] as $key) :
            $path = $key['AvatarPath'];
            if ($path == '')
                $path = '/files/standarts/ava.png'; ?>
            <div class="user-search">
                <div class='img-container'><img width="100" height="100" class='user-poster' src='<?= $path; ?>'></div>
                <div class='text-container'>
                    <a class='user-link' href='/Posts/User/?Id=<?= $key['Login']; ?>'>
                        <?= $key['Login']; ?>
                    </a>
                    <div>
                        <?= $key['FirstName']; ?>
                        <?= $key['SecondName']; ?>
                    </div>

                    <div class="poster-desc"><?= $key['ShortDescription']; ?></div>
                </div>
            </div>
        <?php endforeach ?>
    </div>
</div>