<select id="search">
    <option value="posts" selected>Пости</option>
</select>


<div id="search-result">
<div id="posts">
<div class="row content-row post-block">
    <?php
    foreach($Params['posts'] as $key)
    {
    $path = $key['PosterPath'];
    if($path=='')
        $path = '/files/standarts/reviewPoster.jpg';
    echo "<div class='col-sm-3'>";
    echo"<div class='img-container'><img class='film-poster' src='".$path."'></div>
    <div class='text-container'><a class='poster-link' href='/Posts/Show/?Id=".$key['Id']."'>".$key['Name']."</a></div>
</div>";
}
echo "</div></div></div>";