<div class="tabs search-tabs">
    <ul class="tabs__caption">
        <li class="active">Пости</li>
        <li>Користувачі</li>
    </ul>


    <div class="row content-row post-block tabs__content active">
        <?php

        use Cloudinary\Tag\ImageTag;
        use Cloudinary\Asset\Image;
        use Cloudinary\Transformation\Resize;

        foreach ($Params['posts'] as $key) :
            $path = $key['PosterPath'];
            preg_match('/\/([^\/]*)\./', $path, $matches);
            if (!empty($matches[1])) {
                $path = $matches[1];
            }
            $authorPath = $key['Author']['AvatarPath'];
            preg_match('/\/([^\/]*)\./', $authorPath, $matches);
            if (!empty($matches[1])) {
                $authorPath = $matches[1];
            }
        ?>
            <div class="user-search post-item">
                <div class='img-container'>
                    <div>
                        <?php
                        echo (new ImageTag(new Image($path)))->resize(Resize::fit(277, 150));
                        ?>
                    </div>
                </div>
                <div class='text-container'>
                    <div>
                        <?php echo (new ImageTag(new Image($authorPath)))->resize(Resize::fit(30, 30)); ?>
                        <a class='author-link' href='/Posts/User/<?= $key['Author']['Login']; ?>'><?= $key['Author']['Login']; ?></a>
                    </div>
                    <a class='post-link' href='/Posts/Show/?Id=<?= $key['Id']; ?>'>
                        <?= $key['Name']; ?>
                    </a>
                    <div class='post-content'><?= html_entity_decode($key['Text']); ?></div>
                    <div class='likes-container'>
                        <div class="rating-items">
                            <?php if ($key['LikesUser']) : ?>
                                <a class="unlike-link" href='/Likes/Delete/?post=<?= $key['Id'] ?>'>
                                    <span class='likes glyphicon glyphicon-heart'><?= $key['LikesCount']; ?></span>
                                </a>
                                <a style="display: none;" class="like-link" href='/Likes/Add/?post=<?= $key['Id'] ?>'>
                                    <span class='likes glyphicon glyphicon-heart-empty'><?= $key['LikesCount'] - 1; ?></span>
                                </a>
                            <?php else : ?>
                                <a class="like-link" href='/Likes/Add/?post=<?= $key['Id'] ?>'>
                                    <span class='likes glyphicon glyphicon-heart-empty'><?= $key['LikesCount']; ?></span>
                                </a>
                                <a style="display: none;" class="unlike-link" href='/Likes/Delete/?post=<?= $key['Id'] ?>'>
                                    <span class='likes glyphicon glyphicon-heart'><?= $key['LikesCount'] + 1; ?></span>
                                </a>
                            <?php endif; ?>
                            <span class='comments glyphicon glyphicon-comment'><?= $key['CommentsCount']; ?></span>
                        </div>
                        <div class="publication-date">
                            <span><?= date('d-m-Y', strtotime($key['PublicationDate'])); ?></span>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>

        <?php if (count($Params['posts']) == 0):?> 
                <div class="no-result">
                    Схоже, що по вашому запиту не знайдено записів
                </div>
            <?php endif;?>
    </div>

    <div class="row content-row following-search tabs__content">
        <?php foreach ($Params['users'] as $key) : ?>
            <div class="following-item">
                <div class="following-image">
                    <a href='/Posts/User/<?= $key['Login'] ?>'>
                        <?php
                        $avatarPath = $key['AvatarPath'];
                        preg_match('/\/([^\/]*)\./', $avatarPath, $matches);
                        if (!empty($matches[1])) {
                            $key['AvatarPath'] = $matches[1];
                        }
                        echo (new ImageTag(new Image($key['AvatarPath'])))->resize(Resize::fit(100, 100));
                        ?>
                    </a>
                </div>
                <div class="following-name">
                    <div>
                        <a class="following-name-short" href='/Posts/User/<?= $key['Login'] ?>'>
                            <div>
                                <?= $key['Login'] ?>
                            </div>
                        </a>
                        <div class="following-name-full">
                            <span><?= $key['FirstName'] ?></span>
                            <span><?= $key['SecondName'] ?></span>
                        </div>
                    </div>
                    <div>
                        <a class="unfollow-link" href='/Subscriptions/Delete/?follow=<?= $key['Login'] ?>'>Unfollow</a>
                        <a style="display: none;" class="follow-link" href='/Subscriptions/Add/?follow=<?= $key['Login'] ?>'>Follow</a>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
        <?php if (count($Params['users']) == 0):?> 
                <div class="no-result">
                    Схоже, що по вашому запиту не знайдено користувачів
                </div>
        <?php endif;?>
    </div>
</div>