<?php $isCurrentUserPage = !!($_SESSION['login'] ==  $Params['Author']['Login']); ?>
<div class="posts-container">
    <div class="user-row sticky">
        <img width="200" height="200" class='user-avatar' src='<?= $Params['Author']['AvatarPath']; ?>'>
        <div class="user-info">
            <div><?= $Params['Author']['Country'] . ', ' . $Params['Author']['City']; ?></div>
            <div><?= $Params['Author']['ShortDescription']; ?></div>
            <div>
                <?php if (!$isCurrentUserPage && $Params['Subscription']) : ?>
                    <a class="unfollow-link" href='/Subscriptions/Delete/?follow=<?= $Params['Author']['Login'] ?>'>Unfollow</a>
                    <a style="display: none;" class="follow-link" href='/Subscriptions/Add/?follow=<?= $Params['Author']['Login'] ?>'>Follow</a>
                <?php elseif (!$isCurrentUserPage && !$Params['Subscription']) : ?>
                    <a class="follow-link" href='/Subscriptions/Add/?follow=<?= $Params['Author']['Login'] ?>'>Follow</a>
                    <a style="display: none;" class="unfollow-link" href='/Subscriptions/Delete/?follow=<?= $Params['Author']['Login'] ?>'>Unfollow</a>
                <?php endif; ?>
            </div>
        </div>

        <?php if ($isCurrentUserPage) : ?>
            <a class='btn btn-raised btn-danger btn-prof-set btn-add-post' href='/Posts/Add/'>
                <span class='glyphicon glyphicon-plus' aria-hidden='true'>Додати</span>
            </a>
        <?php endif; ?>
    </div>


    <div class="row content-row posts-block">
        <?php foreach ($Params['Content'] as $key) :
            $path = $key['PosterPath'];
            if (!$key['PosterPath']) {
                $path = '/files/standarts/reviewPoster.jpg';
            } ?>

            <div class='post-item'>
                <?php if ($key['isUserPost']) : ?>
                    <div class='admin-panel'>
                        <a class='btn btn-raised btn-danger btn-prof-set' href='/Posts/Delete/?Id=<?= $key['Id']; ?>'>
                            <span class='glyphicon glyphicon-remove' aria-hidden='true'></span>
                        </a>
                        <a class='btn btn-raised btn-danger btn-prof-set' href='/Posts/Edit/?Id=<?= $key['Id']; ?>'>
                            <span class='glyphicon glyphicon-edit' aria-hidden='true'></span>
                        </a>
                    </div>
                <?php endif; ?>

                <div class='img-container'>
                    <img class='post-poster' src='<?= $path; ?>'>
                    <span><?= $key['PublicationDate']; ?></span>
                </div>
                <div class='text-container'>
                    <div>
                        <img width="30" height="30" class='user-logo' src='<?= $Params['Author']['AvatarPath']; ?>'>
                        <a class='author-link' href='/Posts/User/<?= $Params['Author']['Login']; ?>'><?= $Params['Author']['Login']; ?></a>
                    </div>
                    <a class='poster-link' href='/Posts/Show/?Id=<?= $key['Id']; ?>'><?= $key['Name']; ?></a>
                    <div class='poster-content'><?= html_entity_decode($key['Text']); ?></div>

                    <div class='likes-container'>
                        <?php if ($key['LikesUser']) : ?>
                            <a class="unlike-link" href='/Likes/Delete/?post=<?= $key['Id'] ?>'>
                                <span class='likes glyphicon glyphicon-heart'><?= $key['LikesCount']; ?></span>
                            </a>
                            <a style="display: none;" class="like-link" href='/Likes/Add/?post=<?= $key['Id'] ?>'>
                                <span class='likes glyphicon glyphicon-heart-empty'><?= $key['LikesCount'] - 1; ?></span>
                            </a>
                        <?php else : ?>
                            <a class="like-link" href='/Likes/Add/?post=<?= $key['Id'] ?>'>
                                <span class='likes glyphicon glyphicon-heart-empty'><?= $key['LikesCount']; ?></span>
                            </a>
                            <a style="display: none;" class="unlike-link" href='/Likes/Delete/?post=<?= $key['Id'] ?>'>
                                <span class='likes glyphicon glyphicon-heart'><?= $key['LikesCount'] + 1; ?></span>
                            </a>
                        <?php endif; ?>
                        <span class='views glyphicon glyphicon-eye-open'><?= $key['Views']; ?></span>
                        <span class='comments glyphicon glyphicon-comment'><?= $key['CommentsCount']; ?></span>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
    </div>


    <div class='pagination-div'>
        <ul class='pagination'>
            <li><a href='/Posts/User/?page=1'>«</a></li>
            <?php for ($i = 1; $i <= $Params['PagesCount']; $i++) {
                if ($Params['CurrentPage'] == ($i - 1)) : ?>
                    <li class='active'><a href='/Posts/User/<?= $Params['Author']['Login'] . '/?page=' . $i ?>'><?= $i; ?></a></li>
                <?php else : ?>
                    <li><a href='/Posts/User/<?= $Params['Author']['Login'] . '/?page=' . $i ?>'><?= $i; ?></a></li>
            <?php endif;
            } ?>
            <li><a href='/Posts/User/?page=<?= $Params['PagesCount'] ?>'>»</a></li>
        </ul>
    </div>
</div>

<script src="/templates/js/posts/like.js"></script>