<?php $isCurrentUserPage = !!($_SESSION['login'] ==  $Params['Author']['Login']); ?>
<div class="posts-container">
    <div class="user-row sticky">
        <?php

        use Cloudinary\Tag\ImageTag;
        use Cloudinary\Asset\Image;
        use Cloudinary\Transformation\Resize;

        $ownerPath = $Params['Author']['AvatarPath'];
        preg_match('/\/([^\/]*)\./', $ownerPath, $matches);
        if (!empty($matches[1])) {
            $ownerPath = $matches[1];
        }
        echo (new ImageTag(new Image($ownerPath)))->resize(Resize::fit(200, 200));
        ?>
        <div class="user-info">
            <div class="login"><?= $Params['Author']['Login'] ?></div>
            <div class="location"><?= $Params['Author']['Country'] . ', ' . $Params['Author']['City']; ?></div>
            <div class="about"><?= $Params['Author']['ShortDescription']; ?></div>
            <div>
                <?php if (!$isCurrentUserPage && $Params['Subscription']) : ?>
                    <a class="unfollow-link" href='/Subscriptions/Delete/?follow=<?= $Params['Author']['Login'] ?>'>Unfollow</a>
                    <a style="display: none;" class="follow-link" href='/Subscriptions/Add/?follow=<?= $Params['Author']['Login'] ?>'>Follow</a>
                <?php elseif (!$isCurrentUserPage && !$Params['Subscription']) : ?>
                    <a class="follow-link" href='/Subscriptions/Add/?follow=<?= $Params['Author']['Login'] ?>'>Follow</a>
                    <a style="display: none;" class="unfollow-link" href='/Subscriptions/Delete/?follow=<?= $Params['Author']['Login'] ?>'>Unfollow</a>
                <?php endif; ?>
            </div>
        </div>

        <?php if ($isCurrentUserPage) : ?>
            <a class='btn btn-raised btn-danger btn-prof-set btn-add-post' href='/Posts/Add/'>
                <span class='glyphicon glyphicon-plus' aria-hidden='true'>Додати</span>
            </a>
        <?php endif; ?>
    </div>


    <div class="row content-row posts-block">
        <?php
        foreach ($Params['Content'] as $key) :
            $path = $key['PosterPath'];
            preg_match('/\/([^\/]*)\./', $path, $matches);
            if (!empty($matches[1])) {
                $path = $matches[1];
            }
            $authorPath = $Params['Author']['AvatarPath'];
            preg_match('/\/([^\/]*)\./', $authorPath, $matches);
            if (!empty($matches[1])) {
                $authorPath = $matches[1];
            }
        ?>

            <div class='post-item'>
                <div class='img-container'>
                    <div class="image">
                        <?php
                        echo (new ImageTag(new Image($path)))->resize(Resize::fit(277, 150));
                        ?>
                    </div>
                    <?php if ($key['isUserPost']) : ?>
                        <div class='admin-panel'>
                            <a class='btn btn-raised btn-danger btn-prof-set' href='/Posts/Delete/?Id=<?= $key['Id']; ?>'>
                                <span class='glyphicon glyphicon-remove' aria-hidden='true'></span>
                            </a>
                            <a class='btn btn-raised btn-danger btn-prof-set' href='/Posts/Edit/?Id=<?= $key['Id']; ?>'>
                                <span class='glyphicon glyphicon-edit' aria-hidden='true'></span>
                            </a>
                        </div>
                    <?php endif; ?>
                </div>
                <div class='text-container'>
                    <div>
                        <a class='author-link' href='/Posts/User/<?= $Params['Author']['Login']; ?>'>
                            <?php echo (new ImageTag(new Image($authorPath)))->resize(Resize::fit(30, 30)); ?>
                            <span><?= $Params['Author']['Login']; ?></span>
                        </a>
                    </div>
                    <a class='post-link' href='/Posts/Show/?Id=<?= $key['Id']; ?>'><?= $key['Name']; ?></a>
                    <div class='post-content'><?= html_entity_decode($key['Text']); ?></div>

                    <div class='likes-container'>
                        <div class="rating-items">
                            <?php if ($key['LikesUser']) : ?>
                                <a class="unlike-link" href='/Likes/Delete/?post=<?= $key['Id'] ?>'>
                                    <span class='likes glyphicon glyphicon-heart'><?= $key['LikesCount']; ?></span>
                                </a>
                                <a style="display: none;" class="like-link" href='/Likes/Add/?post=<?= $key['Id'] ?>'>
                                    <span class='likes glyphicon glyphicon-heart-empty'><?= $key['LikesCount'] - 1; ?></span>
                                </a>
                            <?php else : ?>
                                <a class="like-link" href='/Likes/Add/?post=<?= $key['Id'] ?>'>
                                    <span class='likes glyphicon glyphicon-heart-empty'><?= $key['LikesCount']; ?></span>
                                </a>
                                <a style="display: none;" class="unlike-link" href='/Likes/Delete/?post=<?= $key['Id'] ?>'>
                                    <span class='likes glyphicon glyphicon-heart'><?= $key['LikesCount'] + 1; ?></span>
                                </a>
                            <?php endif; ?>
                            <span class='views glyphicon glyphicon-eye-open'><?= $key['Views']; ?></span>
                            <span class='comments glyphicon glyphicon-comment'><?= $key['CommentsCount']; ?></span>
                        </div>
                        <div class="publication-date"><?= $key['PublicationDate']; ?></div>
                    </div>
                </div>
            </div>
        <?php endforeach ?>

        <?php if (count($Params['Content']) == 0) : ?>
            <div class="no-result">
                Схоже, що цей користувач ще не має публікацій
            </div>
        <?php endif; ?>
    </div>

    <?php if (count($Params['Content']) != 0) : ?>
        <div class='pagination-div'>
            <ul class='pagination'>
                <li><a href='/Posts/User/?page=1'>«</a></li>
                <?php for ($i = 1; $i <= $Params['PagesCount']; $i++) {
                    if ($Params['CurrentPage'] == ($i - 1)) : ?>
                        <li class='active'><a href='/Posts/User/<?= $Params['Author']['Login'] . '/?page=' . $i ?>'><?= $i; ?></a></li>
                    <?php else : ?>
                        <li><a href='/Posts/User/<?= $Params['Author']['Login'] . '/?page=' . $i ?>'><?= $i; ?></a></li>
                <?php endif;
                } ?>
                <li><a href='/Posts/User/?page=<?= $Params['PagesCount'] ?>'>»</a></li>
            </ul>
        </div>
    <?php endif; ?>
</div>

<script src="/templates/js/posts/like.js"></script>