<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title><?php echo ($Title); ?></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href='/templates/css/style.css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-inverse">
            <div class="header-wrapper">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <a class="navbar-brand logo-container" href="/Posts/Index/"><img class='logo' src="/files/standarts/films-logo-.png"></a>
                    </div>
                    <div class="burger-block">
                        <input type="checkbox" class="hamburger-input" />
                        <span class="hamburger first-burger"></span>
                        <span class="hamburger"></span>
                        <span class="hamburger last-burger"></span>
                        <ul class="nav navbar-nav menu-nav">
                            <li><a href="/Posts/Index">Головна</a></li>
                            <li><a href="/Posts/User/<?php echo ($_SESSION['login']); ?>">Мої пости</a></li>
                            <li><a href="/Subscriptions/Index">Підписки</a></li>
                            <li><a href="#">Категорії</a></li>
                        </ul>
                    </div>
                    <form class="navbar-form navbar-left" action="/Posts/Search/" method="post">
                        <div class="input-group">
                            <input type="text" class="form-control search-input" placeholder="Пошук" name="searchParam">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit">
                                    <i class="glyphicon glyphicon-search"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                    <ul class="nav navbar-nav navbar-right">
                        <?php
                        if (isset($_SESSION['authorized']) && $_SESSION['authorized'] == true) {
                            echo "<li><a href='/Users/Logout'><span class='glyphicon glyphicon-log-in'></span> Вийти</a></li>
                    <li><a href='/Users/Profile'><span class='glyphicon glyphicon-user'></span>
                        " . $_SESSION['login'] . "</a></li>
                    ";
                        } else {
                            echo "
                    <li><a href='/Users/Login'><span class='glyphicon glyphicon-log-in'></span> Увійти</a></li>
                    <li><a href='/Users/Register'><span class='glyphicon glyphicon-user'></span> Реєстрація</a></li>
                    ";
                        }
                        ?>
                    </ul>
                </div>
            </div>

        </nav>
    </header>
    <main>
        <div class="container">
            <?php echo ($Content) ?>
        </div>
    </main>
    <footer class="nb-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="about">
                        <div class="social-media">
                            <ul class="list-inline">
                                <li><a target="_blank" href="https://www.facebook.com/profile.php?id=100017371837816" title=""><i class="fa fa-facebook"></i></a></li>
                                <li><a target="_blank" href="https://www.instagram.com/melissa_k1t/" title=""><i class="fa fa-instagram"></i></a></li>
                                <li><a target="_blank" href="https://plus.google.com/u/0/113311967906782135581" title=""><i class="fa fa-google"></i></a>
                                </li>
                                <li><a target="_blank" href="https://t.me/melissa_kit" title=""><i class="fa fa-paper-plane-o"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="copyright">
            <div class="container">
                <div class="row">
                    <div class="footer-text">
                        <p>Copyright © 2021 | All rights reserved | Maryna Vozniuk</p>
                    </div>
                </div>
            </div>
        </section>
    </footer>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="/templates/js/file-input-uplode.js"></script>
    <script src="/templates/js/searchSelect.js"></script>
    <script src="/templates/js/subscription/follow.js"></script>
</body>

</html>